export const neVer = [
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Смирнов",
        "firstName": "Николай",
        "age": 72,
        "family": "не женат",
        "geo": "Санкт-Петербург",
        "geoFrom": "Екатеринбург",
        "arrivalDate": "2023-11-25",
        "status": "переселенец",
        "email": "дмитрий.федоров@example.com",
        "tel": "+7-967-628-2216"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Попов",
        "firstName": "Андрей",
        "age": 20,
        "family": "женат",
        "geo": "Москва",
        "geoFrom": "Самара",
        "arrivalDate": "2023-04-25",
        "status": "гражданин",
        "email": "павел.соколов@example.com",
        "tel": "+7-932-612-1354"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Новиков",
        "firstName": "Алексей",
        "age": 30,
        "family": "разведен",
        "geo": "Казань",
        "geoFrom": "Москва",
        "arrivalDate": "2023-10-29",
        "status": "беженец",
        "email": "николай.федоров@example.com",
        "tel": "+7-936-916-2632"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Михайлов",
        "firstName": "Сергей",
        "age": 24,
        "family": "вдовец",
        "geo": "Омск",
        "geoFrom": "Омск",
        "arrivalDate": "2023-02-20",
        "status": "беженец",
        "email": "павел.иванов@example.com",
        "tel": "+7-968-976-3164"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Смирнов",
        "firstName": "Иван",
        "age": 49,
        "family": "женат",
        "geo": "Казань",
        "geoFrom": "Казань",
        "arrivalDate": "2023-10-02",
        "status": "гражданин",
        "email": "иван.федоров@example.com",
        "tel": "+7-946-599-4825"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Новиков",
        "firstName": "Алексей",
        "age": 57,
        "family": "женат",
        "geo": "Москва",
        "geoFrom": "Самара",
        "arrivalDate": "2023-02-27",
        "status": "беженец",
        "email": "алексей.новиков@example.com",
        "tel": "+7-954-100-5459"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Попов",
        "firstName": "Николай",
        "age": 42,
        "family": "не женат",
        "geo": "Москва",
        "geoFrom": "Санкт-Петербург",
        "arrivalDate": "2023-02-21",
        "status": "беженец",
        "email": "дмитрий.смирнов@example.com",
        "tel": "+7-992-359-4735"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Федоров",
        "firstName": "Николай",
        "age": 23,
        "family": "вдовец",
        "geo": "Казань",
        "geoFrom": "Екатеринбург",
        "arrivalDate": "2023-07-21",
        "status": "гражданин",
        "email": "сергей.кузнецов@example.com",
        "tel": "+7-915-125-8092"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Иванов",
        "firstName": "Дмитрий",
        "age": 61,
        "family": "разведен",
        "geo": "Казань",
        "geoFrom": "Нижний Новгород",
        "arrivalDate": "2023-01-18",
        "status": "гражданин",
        "email": "роман.михайлов@example.com",
        "tel": "+7-946-862-5289"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Михайлов",
        "firstName": "Роман",
        "age": 68,
        "family": "женат",
        "geo": "Новосибирск",
        "geoFrom": "Санкт-Петербург",
        "arrivalDate": "2023-12-13",
        "status": "гражданин",
        "email": "максим.иванов@example.com",
        "tel": "+7-993-514-7795"
    }
];

export const ver = [
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Федоров",
        "firstName": "Иван",
        "age": 74,
        "family": "женат",
        "geo": "Казань",
        "geoFrom": "Казань",
        "arrivalDate": "2023-10-16",
        "status": "гражданин",
        "email": "роман.смирнов@example.com",
        "tel": "+7-976-262-2875",
        "adults": 1,
        "teens": 1,
        "pensioners": 0,
        "disabled": 1,
        "pregnant": 0,
        "description": "Без особых замечаний"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Кузнецов",
        "firstName": "Андрей",
        "age": 71,
        "family": "разведен",
        "geo": "Казань",
        "geoFrom": "Ростов-на-Дону",
        "arrivalDate": "2023-06-16",
        "status": "переселенец",
        "email": "сергей.васильев@example.com",
        "tel": "+7-920-897-4838",
        "adults": 3,
        "teens": 1,
        "pensioners": 1,
        "disabled": 0,
        "pregnant": 0,
        "description": "Без особых замечаний"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Васильев",
        "firstName": "Дмитрий",
        "age": 22,
        "family": "женат",
        "geo": "Челябинск",
        "geoFrom": "Новосибирск",
        "arrivalDate": "2023-04-27",
        "status": "гражданин",
        "email": "максим.смирнов@example.com",
        "tel": "+7-957-214-2716",
        "adults": 3,
        "teens": 1,
        "pensioners": 0,
        "disabled": 1,
        "pregnant": 1,
        "description": "Требуется медицинская помощь"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Кузнецов",
        "firstName": "Александр",
        "age": 61,
        "family": "женат",
        "geo": "Нижний Новгород",
        "geoFrom": "Санкт-Петербург",
        "arrivalDate": "2023-03-21",
        "status": "переселенец",
        "email": "иван.соколов@example.com",
        "tel": "+7-951-878-3646",
        "adults": 3,
        "teens": 3,
        "pensioners": 0,
        "disabled": 1,
        "pregnant": 0,
        "description": "Требуется медицинская помощь"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "lastName": "Иванов",
        "firstName": "Павел",
        "age": 67,
        "family": "женат",
        "geo": "Ростов-на-Дону",
        "geoFrom": "Челябинск",
        "arrivalDate": "2023-05-21",
        "status": "беженец",
        "email": "александр.федоров@example.com",
        "tel": "+7-923-615-7938",
        "adults": 3,
        "teens": 1,
        "pensioners": 2,
        "disabled": 0,
        "pregnant": 1,
        "description": "Требуется юридическая помощь"
    },
];

export const verTasks = [
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 1,
        "teens": 0,
        "pensioners": 1,
        "disabled": 1,
        "pregnant": 0,
        "description": "Требуется медицинская помощь"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 3,
        "teens": 2,
        "pensioners": 2,
        "disabled": 1,
        "pregnant": 0,
        "description": "Без особых замечаний"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 2,
        "teens": 0,
        "pensioners": 2,
        "disabled": 0,
        "pregnant": 1,
        "description": "Без особых замечаний"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 4,
        "teens": 0,
        "pensioners": 1,
        "disabled": 1,
        "pregnant": 1,
        "description": "Без особых замечаний"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 2,
        "teens": 1,
        "pensioners": 1,
        "disabled": 0,
        "pregnant": 1,
        "description": "Нуждается в срочном жилье"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 4,
        "teens": 3,
        "pensioners": 1,
        "disabled": 1,
        "pregnant": 0,
        "description": "Имеется маленький ребенок"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 4,
        "teens": 0,
        "pensioners": 2,
        "disabled": 0,
        "pregnant": 0,
        "description": "Требуется медицинская помощь"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 2,
        "teens": 2,
        "pensioners": 1,
        "disabled": 1,
        "pregnant": 0,
        "description": "Имеется маленький ребенок"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 2,
        "teens": 1,
        "pensioners": 2,
        "disabled": 1,
        "pregnant": 0,
        "description": "Требуется медицинская помощь"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 4,
        "teens": 2,
        "pensioners": 0,
        "disabled": 0,
        "pregnant": 0,
        "description": "Требуется юридическая помощь"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 4,
        "teens": 2,
        "pensioners": 0,
        "disabled": 0,
        "pregnant": 1,
        "description": "Имеется маленький ребенок"
    },
    {
        "id": Math.floor(Math.random() * 100),
        "userId": Math.floor(Math.random() * 100),
        "adults": 4,
        "teens": 1,
        "pensioners": 1,
        "disabled": 1,
        "pregnant": 1,
        "description": "Имеется маленький ребенок"
    }
]