export const verTasks = [
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
        "comment": "",
        "status": 0
    },
];

export const ver = [
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
    {
        "id": Math.floor(Math.random() * 100),
        "fullName": "Николай Петрович",
        "legalType": "ИП",
        "registrationDate": "11.09.2023",
        "registrationCity": "Москва",
        "inn": "10101010",
        "kpp": "01010101010",
        "ogrn": "110010101010100101",
        "webSite": "nicola.com",
        "reportLink": "https://ministerstvo.com",
        "description": "Занимаемся помощью украинцам",
        "contactFullName": "Николай Петрович Терентьев",
        "contactPhone": "88005553535",
        "contactEmail": "nicola@gmail.com",
        "helpTypeMask": 200,
    },
];